### ISSUE TITLE
how do you use this?  

### ISSUE THREAD

**Issue by Skrell** [Boondorl/Weather#1]
Can you please add general "install" instructions?  I'm assuming you simply download the source code and change the extension to pk3 but I'm not 100% sure?

**Comment by Boondorl** [comment]
I'm currently in the process of updating some of the API so I'll add instructions after it's finalized. The main thing is that you have to include the files in your base mod directory and merge overlapping files if necessary. Some of the upcoming changes should hopefully make this easier.

**Comment by Skrell** [comment]
Can't wait!

**Comment by Boondorl** [comment]
Closing this as the new documentation now covers this
