### ISSUE TITLE
Errors when trying to load 

### ISSUE THREAD

**Issue by ghost** [Boondorl/Weather#4]
I'm on GZDoom 4.11.3, and on the latest version of this mod. When I put the mod into my pk3 file and try to load, I get the following error messages:
```
Script error, "template.ipk3:zscript/weather/core/reader.zs" line 40:
Unexpected '{'
Expecting ';'

Script error, "template.ipk3:zscript/weather/core/reader.zs" line 48:
Unexpected 'return'
Expecting end of file or 'include' or 'extend' or 'class' or 'mixin' or 'struct' or 'const' or 'enum'

Script error, "template.ipk3:zscript/weather/core/weatherhandler.zs" line 369:
Unexpected '{'
Expecting ';'
```

**Comment by Boondorl** [comment]
Make sure the version of your ZScript is set to 4.11 within the ZScript lump itself i.e. `version "4.11"`. It appears you're using an older version that doesn't recognize the `foreach` syntax. Note that this is independent of the actual version of GZDoom itself so having the latest executable does not automatically imply it's using the latest ZScript version (the default is 2.3).

**Comment by ghost** [comment]
Ah, thanks for your help! I knew I should've done more research before opening an issue...
